package Modalities;

import scxmlgen.interfaces.IOutput;

public enum Output implements IOutput{
    // -------------------------REDUNDANTES-------------------------
    ROLL_DICE("[FUSION][ROLL_DICE]"),
    BUY_HOUSE("[FUSION][BUY_HOUSE]"),
    END_TURN("[FUSION][END_TURN]"),
    GIVE_UP_GAME("[FUSION][GIVE_UP_GAME]"),
    
    // ------------------------ SINGLE ----------------------
    HELP("[FUSION][HELP]"),
    LIST_OF_COLORS("[FUSION][LIST_OF_COLORS]"),
    GAME_INFO("[FUSION][GAME_INFO]"),
    SELECT("[FUSION][SELECT]"),

        // -------------------------CORES-------------------------
    CHOOSE_COLOR_CYAN("[FUSION][CHOOSE_COLOR_CYAN]"),   
    CHOOSE_COLOR_AZUL("[FUSION][CHOOSE_COLOR_AZUL]"),
    CHOOSE_COLOR_LIME("[FUSION][CHOOSE_COLOR_LIME]"),
    CHOOSE_COLOR_YELLOW("[FUSION][CHOOSE_COLOR_YELLOW]"),
    CHOOSE_COLOR_ORANGE("[FUSION][CHOOSE_COLOR_ORANGE]"),
    CHOOSE_COLOR_RED("[FUSION][CHOOSE_COLOR_RED]"),
    CHOOSE_COLOR_BLUE("[FUSION][CHOOSE_COLOR_BLUE]"),
    CHOOSE_COLOR_WATER("[FUSION][CHOOSE_COLOR_WATER]"),
    CHOOSE_COLOR_GREEN("[FUSION][CHOOSE_COLOR_GREEN]"),
    CHOOSE_COLOR_BROWN("[FUSION][CHOOSE_COLOR_BROWN]"),
    CHOOSE_COLOR_HOTPINK("[FUSION][CHOOSE_COLOR_HOTPINK]"),
    CHOOSE_COLOR_PURPLE("[FUSION][CHOOSE_COLOR_PURPLE]"),
    CHOOSE_COLOR_PINK("[FUSION][CHOOSE_COLOR_PINK]"),
    CHOOSE_COLOR_AMARELO("[FUSION][CHOOSE_COLOR_AMARELO]"),
    CHOOSE_COLOR_LARANJA("[FUSION][CHOOSE_COLOR_LARANJA]"),
    CHOOSE_COLOR_VERMELHO("[FUSION][CHOOSE_COLOR_VERMELHO]"),
    CHOOSE_COLOR_CIANO("[FUSION][CHOOSE_COLOR_CIANO]"),
    CHOOSE_COLOR_VERDE("[FUSION][CHOOSE_COLOR_VERDE]"),
    CHOOSE_COLOR_MARROM("[FUSION][CHOOSE_COLOR_MARROM]"),
    CHOOSE_COLOR_ROSA("[FUSION][CHOOSE_COLOR_ROSA]"),
    CHOOSE_COLOR_ROXO("[FUSION][CHOOSE_COLOR_ROXO]"),
    CHOOSE_COLOR_AGUA("[FUSION][CHOOSE_COLOR_AGUA]"),
    CHOOSE_COLOR_CASTANHO("[FUSION][CHOOSE_COLOR_CASTANHO]"),
    CHOOSE_COLOR_MAGENTA("[FUSION][CHOOSE_COLOR_MAGENTA]"),
    CHOOSE_COLOR_CASTANHA("[FUSION][CHOOSE_COLOR_CASTANHA]"),
    CHOOSE_COLOR_VERDE_LIMA("[FUSION][CHOOSE_COLOR_VERDE_LIMA]"),
    CHOOSE_COLOR_VERMELHA("[FUSION][CHOOSE_COLOR_VERMELHA]"),
    CHOOSE_COLOR_AMAERELA("[FUSION][CHOOSE_COLOR_AMAERELA]"),
    CHOOSE_COLOR_ROXA("[FUSION][CHOOSE_COLOR_ROXA]"),

    // -------------------------COMPLEMENTARES-------------------------
    HELP_GAME_INFO("[FUSION][HELP_GAME_INFO]"),
    HELP_LIST_OF_COLORS("[FUSION][HELP_LIST_OF_COLORS]"),
    ROLL_DICE_BUY_HOUSE("[FUSION][ROLL_DICE_BUY_HOUSE]"),
    ROLL_DICE_COMPLETED("[FUSION][ROLL_DICE_COMPLETED]"),

        // -------------------------CORES-------------------------
    SELECT_COLOR_CYAN("[FUSION][SELECT_COLOR_CYAN]"),
    SELECT_COLOR_AZUL("[FUSION][SELECT_COLOR_AZUL]"),
    SELECT_COLOR_LIME("[FUSION][SELECT_COLOR_LIME]"),
    SELECT_COLOR_YELLOW("[FUSION][SELECT_COLOR_YELLOW]"),
    SELECT_COLOR_ORANGE("[FUSION][SELECT_COLOR_ORANGE]"),
    SELECT_COLOR_RED("[FUSION][SELECT_COLOR_RED]"),
    SELECT_COLOR_BLUE("[FUSION][SELECT_COLOR_BLUE]"),
    SELECT_COLOR_WATER("[FUSION][SELECT_COLOR_WATER]"),
    SELECT_COLOR_GREEN("[FUSION][SELECT_COLOR_GREEN]"),
    SELECT_COLOR_BROWN("[FUSION][SELECT_COLOR_BROWN]"),
    SELECT_COLOR_HOTPINK("[FUSION][SELECT_COLOR_HOTPINK]"),
    SELECT_COLOR_PURPLE("[FUSION][SELECT_COLOR_PURPLE]"),
    SELECT_COLOR_PINK("[FUSION][SELECT_COLOR_PINK]"),
    SELECT_COLOR_AMARELO("[FUSION][SELECT_COLOR_AMARELO]"),
    SELECT_COLOR_LARANJA("[FUSION][SELECT_COLOR_LARANJA]"),
    SELECT_COLOR_VERMELHO("[FUSION][SELECT_COLOR_VERMELHO]"),
    SELECT_COLOR_CIANO("[FUSION][SELECT_COLOR_CIANO]"),
    SELECT_COLOR_VERDE("[FUSION][SELECT_COLOR_VERDE]"),
    SELECT_COLOR_MARROM("[FUSION][SELECT_COLOR_MARROM]"),
    SELECT_COLOR_ROSA("[FUSION][SELECT_COLOR_ROSA]"),
    SELECT_COLOR_ROXO("[FUSION][SELECT_COLOR_ROXO]"),
    SELECT_COLOR_AGUA("[FUSION][SELECT_COLOR_AGUA]"),
    SELECT_COLOR_CASTANHO("[FUSION][SELECT_COLOR_CASTANHO]"),
    SELECT_COLOR_MAGENTA("[FUSION][SELECT_COLOR_MAGENTA]"),
    SELECT_COLOR_CASTANHA("[FUSION][SELECT_COLOR_CASTANHA]"),
    SELECT_COLOR_VERDE_LIMA("[FUSION][SELECT_COLOR_VERDE_LIMA]"),
    SELECT_COLOR_VERMELHA("[FUSION][SELECT_COLOR_VERMELHA]"),
    SELECT_COLOR_AMAERELA("[FUSION][SELECT_COLOR_AMAERELA]"),
    SELECT_COLOR_ROXA("[FUSION][SELECT_COLOR_ROXA]"),


    ;
    
    
    
    private String event;

    Output(String m) {
        event=m;
    }
    
    public String getEvent(){
        return this.toString();
    }

    public String getEventName(){
        return event;
    }
}
